### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by lyccyl1** [zyayoung/Iter-Deformable-DETR#12]
When I try to eval with the pretained model.
I miss this error. I have the cofig right. Asking for your help.

**Comment by lyccyl1** [comment]
The error traceback:
Traceback (most recent call last):
  File "demo_opt.py", line 470, in <module>
    eval_results = _evaluate_predictions_on_crowdhuman(gt_path, fpath)
  File "demo_opt.py", line 448, in _evaluate_predictions_on_crowdhuman
    database = Database(gt_path, dt_path, target_key, None, mode)
  File "demo_opt.py", line 311, in __init__
    self.loadData(gtpath, body_key, head_key, if_gt=True)
  File "demo_opt.py", line 326, in loadData
    self.images[record["ID"]] = Image(self.eval_mode)
TypeError: list indices must be integers or slices, not str

**Comment by Yamahhh** [comment]
I got the same error, have you solved it yet?
