### ISSUE TITLE
What versions of pytorch and python do you use?

### ISSUE THREAD

**Issue by ma3252788** [zyayoung/Iter-Deformable-DETR#4]
I use the newest code, but when I evaluate it directly, I got the error:
```
  0%|                                                                                                                                                                                      | 0/4370 [00:00<?, ?it/s]loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
Process Process-1:
Traceback (most recent call last):
  File "/home/sipl/anaconda3/envs/e2edet_new/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sipl/anaconda3/envs/e2edet_new/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "testing.py", line 166, in processor
    checkpoint = torch.load(model_file, map_location='cpu')
  File "/home/sipl/anaconda3/envs/e2edet_new/lib/python3.8/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/sipl/anaconda3/envs/e2edet_new/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
```

Could you tell me how to solve it?

Thank you!!

**Comment by zyayoung** [comment]
Maybe you can try this?
```
pytorch                   1.8.1           py3.7_cuda10.2_cudnn7.6.5_0
torchvision               0.9.1                py37_cu102
```
😃
